### ISSUE TITLE
Inability to output or save files

### ISSUE THREAD

**Issue by Den1604** [star-haven/star-rod#3]
The following error gets output when trying to save a map file. A similar one occurs for all other tools.
This also includes the config and makes it crash upon changing tool.

class java.io.IOException
  at org.apache.commons.io.FileUtils.touch(FileUtils.java:440)
  at game.map.editor.map.Map.saveMapAs_impl(Map.java:746)
  at game.map.editor.map.Map.saveMap(Map.java:729)
  at game.map.editor.MapEditor.action_SaveMap(MapEditor.java:3676)
  at game.map.editor.MapEditor.handleShortcutPress(MapEditor.java:2920)
  at game.map.editor.MapEditor.handleKeyEvent(MapEditor.java:2236)
  at game.map.editor.MapEditor.keyPress(MapEditor.java:2193)
  at game.map.editor.common.KeyboardInput.update(KeyboardInput.java:93)
  at game.map.editor.MapEditor.step(MapEditor.java:1265)
  at game.map.editor.MapEditor.runLoop(MapEditor.java:1209)
  at game.map.editor.MapEditor.launch(MapEditor.java:616)
  at game.map.editor.MapEditor.launch(MapEditor.java:569)
  at main.StarRodDecomp.lambda$action_openMapEditor$11(StarRodDecomp.java:301)
  at main.StarRodDecomp$EditorWorker.doInBackground(StarRodDecomp.java:285)
  at main.StarRodDecomp$EditorWorker.doInBackground(StarRodDecomp.java:270)
  at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by bates64** [comment]
This was an issue on your machine, right? That's been resolved?

**Comment by Den1604** [comment]
Correct, but the fix was weird and it should not have happened to begin with.
If anyone encounters this in the future, the fix for me was to make a backup and then replace the original files with the backup.
